# Generated by Django 4.2.7 on 2023-11-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Board',
            field=models.CharField(max_length=20),
        ),
    ]
